#!/bin/bash
ABSOLUTE_PATH="$(pwd)"
SETUP_FILE="$ABSOLUTE_PATH/devxio/sh"

pip install -r requirements.txt

make build

alias container="docker run -it --rm -v $ABOLUTE_PATH/devxio/:/devxio -v $ABOLUTE_PATH/.runtime/dynamic/:/dynamic -v $ABOLUTE_PATH/.runtime/docs/:/docs docker-template:latest"

# Start de container en voer het init ghost commando uit
docker run -it --rm docker-template boilerplate init ghost

sudo chown -R $USER:$USER $SETUP_FILE
sudo chmod +x $SETUP_FILE
# Source de gegenereerde scripts voor deze shell
source $SETUP_FILE
