#!/bin/bash
SETUP_FILE="/helpers/bash.devxio"
ABSOLUTE_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/$(basename "${BASH_SOURCE[0]}")"   
make build

# Start de container en voer het init ghost commando uit
docker run -it --rm docker-template boilerplate init ghost

# (Optioneel) Haal de gegenereerde scripts op indien nodig
sudo chmod +x $(pwd)/$SETUP_FILE

# Source de gegenereerde scripts voor deze shell
source "$(pwd)/$SETUP_FILE"
