#!/bin/bash

# Generated with Dev-X-io Boilerplate

export ABSOLUTE_PATH="$(pwd)"
export DEVXIO_PATH="$ABSOLUTE_PATH/devxio"
export DEVXIO_FILE="$DEVXIO_PATH/sh"
export DYNAMIC_PATH="$ABSOLUTE_PATH/.runtime/dynamic"
export DOCS_PATH="$ABSOLUTE_PATH/.runtime/docs"



# Read the source containers from .devxio file line by line
while IFS= read -r docker_image
do
    PREFIX=$(echo $docker_image | sed 's/docker-//; s/:.*//')

    function devxio() {
        local command="$1"
        shift  # Shift the arguments to get subcommands and options
        local subcommand="$1"
        shift  # Shift again to get any further options

        case "$command" in
        
        "init")
            case "$subcommand" in
            
            *)
                echo "Unknown subcommand: $subcommand for command init"
                ;;
            esac
            ;;
        
        *)
            echo "Unknown command: $command"
            ;;
        esac
    }
done < .devxio

# Generate the devxio file