#!/bin/bash

# Generated with Dev-X-io Boilerplate

# Read the source containers from .devxio file line by line
while IFS= read -r docker_image
do
    PREFIX=$(echo $docker_image | sed 's/docker-//; s/:.*//')

    function devxio() {
        local command="$1"
        shift  # Shift the arguments to get subcommands and options
        local subcommand="$1"
        shift  # Shift again to get any further options

        case "$command" in
        
        "init")
            case "$subcommand" in
            
            *)
                echo "Unknown subcommand: $subcommand for command init"
                ;;
            esac
            ;;
        
        *)
            echo "Unknown command: $command"
            ;;
        esac
    }
done < .devxio

alias container="docker run -it --rm -v ./helpers/:/devxio -v /workspaces/docker-template/.runtime/boilerplates/:/boilerplates -v /workspaces/docker-template/.runtime/docs/:/docs docker-template:latest"

alias devxio=devxio

echo "Available commands:"

echo "devxio init []"
